(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Gianluca, Welcome to Coot version 0.9")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Gianluca. Welcome to Coot 0.9")
(set-display-lists-for-maps 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "6z4u.pdb" 1)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/mntdirect/_data_id30a3_inhouse/gianluca/coronavirus_structural_task_force/pdb/nucleocapsid_protein/SARS-CoV-2/6z4u/6z4u.mtz" "FWT" "PHWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "/mntdirect/_data_id30a3_inhouse/gianluca/coronavirus_structural_task_force/pdb/nucleocapsid_protein/SARS-CoV-2/6z4u/6z4u.mtz" "DELFWT" "PHDELWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
