filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Gianluca, Welcome to Coot version 0.9.3")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning Gianluca. Welcome to Coot 0.9.3")
set_display_lists_for_maps (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
