filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Gianluca, Welcome to Coot version 0.9")
use_graphics_interface_state ()
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning Gianluca. Welcome to Coot 0.9")
set_display_lists_for_maps (1)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/mntdirect/_data_id30a3_inhouse/gianluca/coronavirus_structural_task_force/pdb/surface_glycoprotein/SARS-CoV-2/6zgg/6zgg.cif", 1)
